/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class CourseAlreadyExists extends javax.swing.JFrame {

    /**
     * Creates new form CourseAlreadyExists
     */
    public CourseAlreadyExists() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CourseAlreadyExistsPanel = new javax.swing.JPanel();
        CourseAlreadyExistsText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        CourseAlreadyExistsPanel.setBackground(new java.awt.Color(63, 193, 201));
        CourseAlreadyExistsPanel.setMinimumSize(new java.awt.Dimension(200, 100));

        CourseAlreadyExistsText.setEditable(false);
        CourseAlreadyExistsText.setBackground(new java.awt.Color(63, 193, 201));
        CourseAlreadyExistsText.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CourseAlreadyExistsText.setForeground(new java.awt.Color(245, 245, 245));
        CourseAlreadyExistsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CourseAlreadyExistsText.setText("Course Already Exist");
        CourseAlreadyExistsText.setBorder(null);
        CourseAlreadyExistsText.setFocusable(false);

        javax.swing.GroupLayout CourseAlreadyExistsPanelLayout = new javax.swing.GroupLayout(CourseAlreadyExistsPanel);
        CourseAlreadyExistsPanel.setLayout(CourseAlreadyExistsPanelLayout);
        CourseAlreadyExistsPanelLayout.setHorizontalGroup(
            CourseAlreadyExistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseAlreadyExistsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(CourseAlreadyExistsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        CourseAlreadyExistsPanelLayout.setVerticalGroup(
            CourseAlreadyExistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseAlreadyExistsPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(CourseAlreadyExistsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseAlreadyExistsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourseAlreadyExistsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseAlreadyExists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseAlreadyExistsPanel;
    private javax.swing.JTextField CourseAlreadyExistsText;
    // End of variables declaration//GEN-END:variables
}
