/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.KeyEvent;

/**
 *
 * @author LENOVO
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePageTest
     */
    public HomePage() {
        initComponents();
        // Set Title
        this.setTitle("Office and Class Allocation System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        HomePageText = new javax.swing.JTextField();
        Admin = new javax.swing.JPanel();
        AdminIconButton = new javax.swing.JButton();
        AdminLabel = new javax.swing.JLabel();
        Instructor = new javax.swing.JPanel();
        InstructorIconButton = new javax.swing.JButton();
        InstructorLabel = new javax.swing.JLabel();
        Student = new javax.swing.JPanel();
        StudentIconButton = new javax.swing.JButton();
        StudentLabel = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        DevelopedBy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        HomePagePanel.setBackground(new java.awt.Color(54, 79, 107));

        Header.setBackground(new java.awt.Color(63, 193, 201));

        HomePageText.setEditable(false);
        HomePageText.setBackground(new java.awt.Color(63, 193, 201));
        HomePageText.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        HomePageText.setForeground(new java.awt.Color(255, 255, 255));
        HomePageText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HomePageText.setText("Home Page");
        HomePageText.setBorder(null);
        HomePageText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomePageText.setFocusable(false);
        HomePageText.setHighlighter(null);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        Admin.setOpaque(false);
        Admin.setPreferredSize(new java.awt.Dimension(150, 150));

        AdminIconButton.setBackground(new java.awt.Color(59, 79, 107));
        AdminIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-admin-96.png"))); // NOI18N
        AdminIconButton.setToolTipText("");
        AdminIconButton.setBorder(null);
        AdminIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminIconButton.setOpaque(false);
        AdminIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        AdminIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminIconButtonMouseClicked(evt);
            }
        });
        AdminIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminIconButtonKeyPressed(evt);
            }
        });

        AdminLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(245, 245, 245));
        AdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLabel.setText("Admin");
        AdminLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLabelMouseClicked(evt);
            }
        });
        AdminLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(AdminIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(AdminLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AdminIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(AdminLabel)
                .addContainerGap())
        );

        Instructor.setOpaque(false);
        Instructor.setPreferredSize(new java.awt.Dimension(150, 150));

        InstructorIconButton.setBackground(new java.awt.Color(59, 79, 107));
        InstructorIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-teacher-96.png"))); // NOI18N
        InstructorIconButton.setToolTipText("");
        InstructorIconButton.setBorder(null);
        InstructorIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InstructorIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        InstructorIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorIconButtonMouseClicked(evt);
            }
        });
        InstructorIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InstructorIconButtonKeyPressed(evt);
            }
        });

        InstructorLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        InstructorLabel.setForeground(new java.awt.Color(245, 245, 245));
        InstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InstructorLabel.setText("Instructor");
        InstructorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InstructorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorLabelMouseClicked(evt);
            }
        });
        InstructorLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InstructorLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout InstructorLayout = new javax.swing.GroupLayout(Instructor);
        Instructor.setLayout(InstructorLayout);
        InstructorLayout.setHorizontalGroup(
            InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(InstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(InstructorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(InstructorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InstructorLayout.setVerticalGroup(
            InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(InstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(InstructorLabel)
                .addContainerGap())
        );

        Student.setOpaque(false);
        Student.setPreferredSize(new java.awt.Dimension(150, 150));

        StudentIconButton.setBackground(new java.awt.Color(59, 79, 107));
        StudentIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-96.png"))); // NOI18N
        StudentIconButton.setToolTipText("");
        StudentIconButton.setBorder(null);
        StudentIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        StudentIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentIconButtonMouseClicked(evt);
            }
        });
        StudentIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentIconButtonKeyPressed(evt);
            }
        });

        StudentLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        StudentLabel.setForeground(new java.awt.Color(245, 245, 245));
        StudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentLabel.setText("Student");
        StudentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentLabelMouseClicked(evt);
            }
        });
        StudentLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
        Student.setLayout(StudentLayout);
        StudentLayout.setHorizontalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(StudentIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(StudentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentLayout.setVerticalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StudentIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(StudentLabel)
                .addContainerGap())
        );

        Footer.setBackground(new java.awt.Color(63, 193, 201));
        Footer.setPreferredSize(new java.awt.Dimension(0, 30));

        DevelopedBy.setEditable(false);
        DevelopedBy.setBackground(new java.awt.Color(63, 193, 201));
        DevelopedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevelopedBy.setForeground(new java.awt.Color(255, 255, 255));
        DevelopedBy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DevelopedBy.setText("Developed By: Hafiz Muhammad Saad");
        DevelopedBy.setBorder(null);
        DevelopedBy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DevelopedBy.setFocusable(false);
        DevelopedBy.setHighlighter(null);

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminIconButtonMouseClicked
        // TODO add your handling code here:
        LogInAdmin login_admin = new LogInAdmin();
        login_admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminIconButtonMouseClicked

    private void AdminIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogInAdmin login_admin = new LogInAdmin();
            login_admin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AdminIconButtonKeyPressed

    private void AdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLabelMouseClicked
        // TODO add your handling code here:
        LogInAdmin login_admin = new LogInAdmin();
        login_admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminLabelMouseClicked

    private void AdminLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogInAdmin login_admin = new LogInAdmin();
            login_admin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AdminLabelKeyPressed

    private void InstructorIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorIconButtonMouseClicked
        // TODO add your handling code here:
        LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
        login_instructor_student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InstructorIconButtonMouseClicked

    private void InstructorIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructorIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
            login_instructor_student.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_InstructorIconButtonKeyPressed

    private void InstructorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorLabelMouseClicked
        // TODO add your handling code here:
        LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
        login_instructor_student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InstructorLabelMouseClicked

    private void InstructorLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructorLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
            login_instructor_student.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_InstructorLabelKeyPressed

    private void StudentIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentIconButtonMouseClicked
        // TODO add your handling code here:
        LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
        login_instructor_student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentIconButtonMouseClicked

    private void StudentIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
            login_instructor_student.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StudentIconButtonKeyPressed

    private void StudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentLabelMouseClicked
        // TODO add your handling code here:
        LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
        login_instructor_student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentLabelMouseClicked

    private void StudentLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogIn_Instructor_Student login_instructor_student = new LogIn_Instructor_Student();
            login_instructor_student.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StudentLabelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JButton AdminIconButton;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JTextField DevelopedBy;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JTextField HomePageText;
    private javax.swing.JPanel Instructor;
    private javax.swing.JButton InstructorIconButton;
    private javax.swing.JLabel InstructorLabel;
    private javax.swing.JPanel Student;
    private javax.swing.JButton StudentIconButton;
    private javax.swing.JLabel StudentLabel;
    // End of variables declaration//GEN-END:variables
}
