/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.KeyEvent;

/**
 *
 * @author LENOVO
 */
public class HomePageAdmin extends javax.swing.JFrame {

    String email;
    
    public HomePageAdmin() {
        initComponents();
        // Set Title
        this.setTitle("Office and Class Allocation System");
    }

    public HomePageAdmin(String email) {
        initComponents();
        // Set Title
        this.setTitle("Office and Class Allocation System");
        this.email = email;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePageAdminPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Field = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        AdminIconButton = new javax.swing.JButton();
        AdminLabel = new javax.swing.JLabel();
        InstructorPanel = new javax.swing.JPanel();
        InstructorIconButton = new javax.swing.JButton();
        InstructorLabel = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        StudentIconButton = new javax.swing.JButton();
        StudentLabel = new javax.swing.JLabel();
        ClassPanel = new javax.swing.JPanel();
        ClassIconButton = new javax.swing.JButton();
        ClassLabel = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        DevelopedBy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        HomePageAdminPanel.setBackground(new java.awt.Color(54, 79, 107));

        Header.setBackground(new java.awt.Color(63, 193, 201));
        Header.setPreferredSize(new java.awt.Dimension(900, 86));

        Field.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Field.setForeground(new java.awt.Color(245, 245, 245));
        Field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Field.setText("Admin");

        LogoutButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(54, 79, 107));
        LogoutButton.setText("Logout");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.setPreferredSize(new java.awt.Dimension(90, 30));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        LogoutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(804, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Field, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Field))
        );

        AdminPanel.setOpaque(false);
        AdminPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        AdminIconButton.setBackground(new java.awt.Color(59, 79, 107));
        AdminIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-admin-96.png"))); // NOI18N
        AdminIconButton.setToolTipText("");
        AdminIconButton.setBorder(null);
        AdminIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        AdminIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminIconButtonMouseClicked(evt);
            }
        });
        AdminIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminIconButtonKeyPressed(evt);
            }
        });

        AdminLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(245, 245, 245));
        AdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLabel.setText("Admin");
        AdminLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLabelMouseClicked(evt);
            }
        });
        AdminLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(AdminIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(AdminLabel)
                        .addGap(55, 55, 55))))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AdminIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(AdminLabel)
                .addContainerGap())
        );

        InstructorPanel.setOpaque(false);
        InstructorPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        InstructorIconButton.setBackground(new java.awt.Color(54, 79, 107));
        InstructorIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-teacher-96.png"))); // NOI18N
        InstructorIconButton.setBorder(null);
        InstructorIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InstructorIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        InstructorIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorIconButtonMouseClicked(evt);
            }
        });
        InstructorIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InstructorIconButtonKeyPressed(evt);
            }
        });

        InstructorLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        InstructorLabel.setForeground(new java.awt.Color(245, 245, 245));
        InstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InstructorLabel.setText("Instructor");
        InstructorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InstructorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorLabelMouseClicked(evt);
            }
        });
        InstructorLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InstructorLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout InstructorPanelLayout = new javax.swing.GroupLayout(InstructorPanel);
        InstructorPanel.setLayout(InstructorPanelLayout);
        InstructorPanelLayout.setHorizontalGroup(
            InstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(InstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstructorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InstructorLabel)
                .addGap(45, 45, 45))
        );
        InstructorPanelLayout.setVerticalGroup(
            InstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(InstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(InstructorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentPanel.setOpaque(false);
        StudentPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        StudentIconButton.setBackground(new java.awt.Color(59, 79, 107));
        StudentIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-96.png"))); // NOI18N
        StudentIconButton.setBorder(null);
        StudentIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        StudentIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentIconButtonMouseClicked(evt);
            }
        });
        StudentIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentIconButtonKeyPressed(evt);
            }
        });

        StudentLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        StudentLabel.setForeground(new java.awt.Color(245, 245, 245));
        StudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentLabel.setText("Student");
        StudentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentLabelMouseClicked(evt);
            }
        });
        StudentLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPanelLayout.createSequentialGroup()
                        .addComponent(StudentIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPanelLayout.createSequentialGroup()
                        .addComponent(StudentLabel)
                        .addGap(50, 50, 50))))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StudentIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(StudentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ClassPanel.setOpaque(false);
        ClassPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        ClassIconButton.setBackground(new java.awt.Color(54, 79, 107));
        ClassIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-class-96.png"))); // NOI18N
        ClassIconButton.setBorder(null);
        ClassIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        ClassIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassIconButtonMouseClicked(evt);
            }
        });
        ClassIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClassIconButtonKeyPressed(evt);
            }
        });

        ClassLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ClassLabel.setForeground(new java.awt.Color(245, 245, 245));
        ClassLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassLabel.setText("Class");
        ClassLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassLabelMouseClicked(evt);
            }
        });
        ClassLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClassLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ClassPanelLayout = new javax.swing.GroupLayout(ClassPanel);
        ClassPanel.setLayout(ClassPanelLayout);
        ClassPanelLayout.setHorizontalGroup(
            ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClassIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(ClassPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ClassLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        ClassPanelLayout.setVerticalGroup(
            ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ClassIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ClassLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Footer.setBackground(new java.awt.Color(63, 193, 201));
        Footer.setPreferredSize(new java.awt.Dimension(0, 30));

        DevelopedBy.setEditable(false);
        DevelopedBy.setBackground(new java.awt.Color(63, 193, 201));
        DevelopedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevelopedBy.setForeground(new java.awt.Color(255, 255, 255));
        DevelopedBy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DevelopedBy.setText("Developed By: Hafiz Muhammad Saad");
        DevelopedBy.setBorder(null);
        DevelopedBy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DevelopedBy.setFocusable(false);
        DevelopedBy.setHighlighter(null);

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HomePageAdminPanelLayout = new javax.swing.GroupLayout(HomePageAdminPanel);
        HomePageAdminPanel.setLayout(HomePageAdminPanelLayout);
        HomePageAdminPanelLayout.setHorizontalGroup(
            HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageAdminPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(HomePageAdminPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addGroup(HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePageAdminPanelLayout.setVerticalGroup(
            HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageAdminPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomePageAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePageAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePageAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        // TODO add your handling code here:
        HomePage homepage = new HomePage();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void LogoutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            HomePage homepage = new HomePage();
            homepage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutButtonKeyPressed

    private void AdminIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminIconButtonMouseClicked
        // TODO add your handling code here:
        AdminPage adminpage = new AdminPage();
        adminpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminIconButtonMouseClicked

    private void AdminIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            AdminPage adminpage = new AdminPage();
            adminpage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AdminIconButtonKeyPressed

    private void AdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLabelMouseClicked
        // TODO add your handling code here:
        AdminPage adminpage = new AdminPage();
        adminpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminLabelMouseClicked

    private void AdminLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            AdminPage adminpage = new AdminPage();
            adminpage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AdminLabelKeyPressed

    private void InstructorIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorIconButtonMouseClicked
        // TODO add your handling code here:
        new InstructorPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InstructorIconButtonMouseClicked

    private void InstructorIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructorIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new InstructorPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_InstructorIconButtonKeyPressed

    private void InstructorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorLabelMouseClicked
        // TODO add your handling code here:
        new InstructorPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InstructorLabelMouseClicked

    private void InstructorLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructorLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new InstructorPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_InstructorLabelKeyPressed

    private void StudentIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentIconButtonMouseClicked
        // TODO add your handling code here:
        new StudentPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentIconButtonMouseClicked

    private void StudentIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new StudentPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StudentIconButtonKeyPressed
    
    private void StudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentLabelMouseClicked
        // TODO add your handling code here:
        new StudentPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentLabelMouseClicked

    private void StudentLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new StudentPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StudentLabelKeyPressed

    private void ClassIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassIconButtonMouseClicked
        // TODO add your handling code here:
        new ClassPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClassIconButtonMouseClicked

    private void ClassIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClassIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new ClassPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ClassIconButtonKeyPressed

    private void ClassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassLabelMouseClicked
        // TODO add your handling code here:
        new ClassPage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClassLabelMouseClicked

    private void ClassLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClassLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new ClassPage(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ClassLabelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminIconButton;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton ClassIconButton;
    private javax.swing.JLabel ClassLabel;
    private javax.swing.JPanel ClassPanel;
    private javax.swing.JTextField DevelopedBy;
    private javax.swing.JLabel Field;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePageAdminPanel;
    private javax.swing.JButton InstructorIconButton;
    private javax.swing.JLabel InstructorLabel;
    private javax.swing.JPanel InstructorPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton StudentIconButton;
    private javax.swing.JLabel StudentLabel;
    private javax.swing.JPanel StudentPanel;
    // End of variables declaration//GEN-END:variables
}
