/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.KeyEvent;

/**
 *
 * @author LENOVO
 */
public class InstructorPage extends javax.swing.JFrame {

    String email;
    
    public InstructorPage() {
        initComponents();
        // Set Title
        this.setTitle("Office and Class Allocation System");
    }
    
    public InstructorPage(String email) {
        initComponents();
        // Set Title
        this.setTitle("Office and Class Allocation System");
        this.email = email;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InstructorPagePanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Field = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        AddInstructorPanel = new javax.swing.JPanel();
        AddInstructorIconButton = new javax.swing.JButton();
        AddInstructorLabel = new javax.swing.JLabel();
        ShowInstructorPanel = new javax.swing.JPanel();
        ShowInstructorIconButton = new javax.swing.JButton();
        ShowInstructorLabel = new javax.swing.JLabel();
        UpdateInstructorPanel = new javax.swing.JPanel();
        UpdateInstructorIconButton = new javax.swing.JButton();
        UpdateInstructorLabel = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        DevelopedBy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        InstructorPagePanel.setBackground(new java.awt.Color(54, 79, 107));
        InstructorPagePanel.setPreferredSize(new java.awt.Dimension(900, 500));

        Header.setBackground(new java.awt.Color(63, 193, 201));
        Header.setPreferredSize(new java.awt.Dimension(900, 86));

        Field.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Field.setForeground(new java.awt.Color(245, 245, 245));
        Field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Field.setText("Admin");

        LogoutButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(54, 79, 107));
        LogoutButton.setText("Logout");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.setPreferredSize(new java.awt.Dimension(90, 30));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        LogoutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutButtonKeyPressed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(54, 79, 107));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-32.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.setPreferredSize(new java.awt.Dimension(35, 35));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Field, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 728, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Field)
                .addContainerGap())
        );

        AddInstructorPanel.setOpaque(false);
        AddInstructorPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        AddInstructorIconButton.setBackground(new java.awt.Color(59, 79, 107));
        AddInstructorIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-group-woman-man-96.png"))); // NOI18N
        AddInstructorIconButton.setToolTipText("");
        AddInstructorIconButton.setBorder(null);
        AddInstructorIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddInstructorIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        AddInstructorIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddInstructorIconButtonMouseClicked(evt);
            }
        });
        AddInstructorIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddInstructorIconButtonKeyPressed(evt);
            }
        });

        AddInstructorLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AddInstructorLabel.setForeground(new java.awt.Color(245, 245, 245));
        AddInstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddInstructorLabel.setText("Add Instructor");
        AddInstructorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddInstructorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddInstructorLabelMouseClicked(evt);
            }
        });
        AddInstructorLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddInstructorLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout AddInstructorPanelLayout = new javax.swing.GroupLayout(AddInstructorPanel);
        AddInstructorPanel.setLayout(AddInstructorPanelLayout);
        AddInstructorPanelLayout.setHorizontalGroup(
            AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(AddInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(AddInstructorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddInstructorPanelLayout.setVerticalGroup(
            AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AddInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(AddInstructorLabel)
                .addContainerGap())
        );

        ShowInstructorPanel.setOpaque(false);
        ShowInstructorPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        ShowInstructorIconButton.setBackground(new java.awt.Color(59, 79, 107));
        ShowInstructorIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-team-skin-type-7-96.png"))); // NOI18N
        ShowInstructorIconButton.setToolTipText("");
        ShowInstructorIconButton.setBorder(null);
        ShowInstructorIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowInstructorIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        ShowInstructorIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowInstructorIconButtonMouseClicked(evt);
            }
        });
        ShowInstructorIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShowInstructorIconButtonKeyPressed(evt);
            }
        });

        ShowInstructorLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ShowInstructorLabel.setForeground(new java.awt.Color(245, 245, 245));
        ShowInstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowInstructorLabel.setText("Show Instructors");
        ShowInstructorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowInstructorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowInstructorLabelMouseClicked(evt);
            }
        });
        ShowInstructorLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShowInstructorLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ShowInstructorPanelLayout = new javax.swing.GroupLayout(ShowInstructorPanel);
        ShowInstructorPanel.setLayout(ShowInstructorPanelLayout);
        ShowInstructorPanelLayout.setHorizontalGroup(
            ShowInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowInstructorPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(ShowInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(ShowInstructorPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ShowInstructorLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ShowInstructorPanelLayout.setVerticalGroup(
            ShowInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowInstructorPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ShowInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ShowInstructorLabel)
                .addContainerGap())
        );

        UpdateInstructorPanel.setOpaque(false);
        UpdateInstructorPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        UpdateInstructorIconButton.setBackground(new java.awt.Color(59, 79, 107));
        UpdateInstructorIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-user-skin-type-7-96.png"))); // NOI18N
        UpdateInstructorIconButton.setToolTipText("");
        UpdateInstructorIconButton.setBorder(null);
        UpdateInstructorIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateInstructorIconButton.setPreferredSize(new java.awt.Dimension(102, 102));
        UpdateInstructorIconButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateInstructorIconButtonMouseClicked(evt);
            }
        });
        UpdateInstructorIconButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateInstructorIconButtonKeyPressed(evt);
            }
        });

        UpdateInstructorLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        UpdateInstructorLabel.setForeground(new java.awt.Color(245, 245, 245));
        UpdateInstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateInstructorLabel.setText("Update Instructor");
        UpdateInstructorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateInstructorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateInstructorLabelMouseClicked(evt);
            }
        });
        UpdateInstructorLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateInstructorLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout UpdateInstructorPanelLayout = new javax.swing.GroupLayout(UpdateInstructorPanel);
        UpdateInstructorPanel.setLayout(UpdateInstructorPanelLayout);
        UpdateInstructorPanelLayout.setHorizontalGroup(
            UpdateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateInstructorPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(UpdateInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(UpdateInstructorPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(UpdateInstructorLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        UpdateInstructorPanelLayout.setVerticalGroup(
            UpdateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateInstructorPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(UpdateInstructorIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(UpdateInstructorLabel)
                .addContainerGap())
        );

        Footer.setBackground(new java.awt.Color(63, 193, 201));
        Footer.setPreferredSize(new java.awt.Dimension(0, 30));

        DevelopedBy.setEditable(false);
        DevelopedBy.setBackground(new java.awt.Color(63, 193, 201));
        DevelopedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevelopedBy.setForeground(new java.awt.Color(255, 255, 255));
        DevelopedBy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DevelopedBy.setText("Developed By: Hafiz Muhammad Saad");
        DevelopedBy.setBorder(null);
        DevelopedBy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DevelopedBy.setFocusable(false);
        DevelopedBy.setHighlighter(null);

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DevelopedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout InstructorPagePanelLayout = new javax.swing.GroupLayout(InstructorPagePanel);
        InstructorPagePanel.setLayout(InstructorPagePanelLayout);
        InstructorPagePanelLayout.setHorizontalGroup(
            InstructorPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorPagePanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(InstructorPagePanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(AddInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ShowInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(UpdateInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InstructorPagePanelLayout.setVerticalGroup(
            InstructorPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorPagePanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(InstructorPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateInstructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InstructorPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InstructorPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        // TODO add your handling code here:
        HomePage homepage = new HomePage();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void LogoutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            HomePage homepage = new HomePage();
            homepage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutButtonKeyPressed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        if (email.equals("admin@admin.com")) {
            new HomePageAdmin(email).setVisible(true);
            this.dispose();
        } else {
            new HomePageSubAdmin(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (email.equals("admin@admin.com")) {
                new HomePageAdmin(email).setVisible(true);
                this.dispose();
            } else {
                new HomePageSubAdmin(email).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_BackButtonKeyPressed

    private void AddInstructorIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddInstructorIconButtonMouseClicked
        // TODO add your handling code here:
        new AddInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddInstructorIconButtonMouseClicked

    private void AddInstructorIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddInstructorIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new AddInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AddInstructorIconButtonKeyPressed

    private void AddInstructorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddInstructorLabelMouseClicked
        // TODO add your handling code here:
        new AddInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddInstructorLabelMouseClicked

    private void AddInstructorLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddInstructorLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new AddInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AddInstructorLabelKeyPressed

    private void ShowInstructorIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowInstructorIconButtonMouseClicked
        // TODO add your handling code here:
        new ShowInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ShowInstructorIconButtonMouseClicked

    private void ShowInstructorIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShowInstructorIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new ShowInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ShowInstructorIconButtonKeyPressed

    private void ShowInstructorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowInstructorLabelMouseClicked
        // TODO add your handling code here:
        new ShowInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ShowInstructorLabelMouseClicked

    private void ShowInstructorLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShowInstructorLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new ShowInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ShowInstructorLabelKeyPressed

    private void UpdateInstructorIconButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateInstructorIconButtonMouseClicked
        // TODO add your handling code here:
        new UpdateInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateInstructorIconButtonMouseClicked

    private void UpdateInstructorIconButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateInstructorIconButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new UpdateInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_UpdateInstructorIconButtonKeyPressed

    private void UpdateInstructorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateInstructorLabelMouseClicked
        // TODO add your handling code here:
        new UpdateInstructor(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateInstructorLabelMouseClicked

    private void UpdateInstructorLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateInstructorLabelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            new UpdateInstructor(email).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_UpdateInstructorLabelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInstructorIconButton;
    private javax.swing.JLabel AddInstructorLabel;
    private javax.swing.JPanel AddInstructorPanel;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField DevelopedBy;
    private javax.swing.JLabel Field;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel InstructorPagePanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ShowInstructorIconButton;
    private javax.swing.JLabel ShowInstructorLabel;
    private javax.swing.JPanel ShowInstructorPanel;
    private javax.swing.JButton UpdateInstructorIconButton;
    private javax.swing.JLabel UpdateInstructorLabel;
    private javax.swing.JPanel UpdateInstructorPanel;
    // End of variables declaration//GEN-END:variables
}
